# Generated by Django 5.0.6 on 2024-06-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_categoria', '0002_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cat_imagen',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
