# Generated by Django 5.0.6 on 2024-06-27 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_variacion', models.CharField(choices=[('capacidad', 'capacidad'), ('largo', 'largo'), ('tipo', 'tipo'), ('color', 'color')], max_length=100)),
                ('valor_variacion', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_tienda.producto')),
            ],
        ),
    ]
