# Generated by Django 5.0.6 on 2024-06-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_autentificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
