# Generated by Django 5.0.6 on 2024-06-27 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.carro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_tienda.producto')),
            ],
        ),
    ]
