# Generated by Django 5.0.6 on 2024-06-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('m_tienda', '0002_variacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carroitem',
            name='variaciones',
            field=models.ManyToManyField(blank=True, to='m_tienda.variacion'),
        ),
    ]
