# Generated by Django 5.0.6 on 2024-06-28 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_tienda', '0002_variacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('nota_orden', models.CharField(blank=True, max_length=100)),
                ('total_orden', models.FloatField()),
                ('impuesto', models.FloatField()),
                ('estado', models.CharField(choices=[('Nuevo', 'nuevo'), ('Aceptado', 'aceptado'), ('Completado', 'completado'), ('Cancelado', 'cancelado')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_id', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('monto_pago', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(max_length=58)),
                ('largo', models.CharField(max_length=58)),
                ('tipo', models.CharField(max_length=58)),
                ('color', models.CharField(max_length=58)),
                ('cantidad', models.IntegerField()),
                ('precio_producto', models.FloatField()),
                ('ordenado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_tienda.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_tienda.variacion')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.pago')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.pago'),
        ),
    ]
