# Generated by Django 5.0.6 on 2024-07-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'nuevo'), ('Aceptado', 'aceptado'), ('Completado', 'completado'), ('Cancelado', 'cancelado')], default='Nuevo', max_length=10),
        ),
    ]
