# Generated by Django 5.0.6 on 2024-07-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_tienda', '0003_calificacionresenia'),
        ('ordenes', '0003_remove_ordenproducto_capacidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproducto',
            name='variacion',
        ),
        migrations.AddField(
            model_name='ordenproducto',
            name='variaciones',
            field=models.ManyToManyField(blank=True, to='m_tienda.variacion'),
        ),
    ]
